---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(lubridate)
library(rvest)
library(stringr)
library(glue)


#read in reviews
#beer.rev<-read_csv("/Users/sethraithel/Google Drive/beer_reviews/beer_reviews.csv")
#beer<-read_csv("C:/Users/Seth_Raithel/Desktop/Data project/BADV_Data/beer_reviews.csv")
#beer.rev <- read_csv("beer_reviews.csv")

```

```{r}

brewery.id.list <- beer.rev %>% count(brewery_id, sort = TRUE) %>% top_n(n = 100)

brewery.id.list <- brewery.id.list$brewery_id
```

```{r}

scrape_beer <- function(brew_id = 35) {
  #basic brewery landing page
  brew <-
  read_html(glue("https://www.beeradvocate.com/beer/profile/{brew_id}/"))
  
  #beer name
  beer.name <-
  brew %>% html_nodes(".hr_bottom_light:nth-child(1)") %>% html_text()
  
  #brewery name
  brewery.name <- brew %>% html_nodes("h1") %>% html_text()
  
  #beer style name
  beer.style <-
  brew %>% html_nodes(".hr_bottom_light:nth-child(2)") %>% html_text()
  
  #beer abv
  beer.abv <-
  brew %>% html_nodes(".hr_bottom_light:nth-child(3)") %>% html_text()
  
  beer.num <- brew %>% html_nodes(".hr_bottom_light:nth-child(4)") %>% html_text()
  beer.num <- str_replace_all(beer.num, ",","")
  
  beer_urls <-
  brew %>% html_nodes(".hr_bottom_light:nth-child(1)") %>% html_nodes("a") %>%  html_attr('href')
  
  beer.id <- str_split(beer_urls, paste0("/beer/profile/",brew_id,"/"))
  beer.id <-  str_extract_all(beer.id, pattern = "[\\d.]+", simplify = TRUE
  )
  
  beer_urls <- paste0("https://www.beeradvocate.com/", beer_urls)
  
  beer_info <- data.frame(beer.name, beer.style, beer.abv, beer_urls, beer.id, "brewery.id"=brew_id, brewery.name, beer.num)
  beer_info <- beer_info[which(as.numeric(as.character(beer_info$beer.num)) >= 10),]
  return(beer_info)
}

#beer.urls<- beer.url.pages[1]
#beer.urls <- paste0(brewery$beer_urls[71],"?view=beer&sort=&start=",150)

grab_reviews <- function(beer.urls) {
  
  beer <- read_html(as.character(beer.urls))
  
  #find review with no raitings and index
  index <-
  str_detect(beer %>% html_nodes("#rating_fullview_container") %>% html_text(),
  "\\| smell:")
  
  beer.review <- beer %>% html_nodes("#rating_fullview_container")
  beer.review <- beer.review[which(index == TRUE)]
  if (length(beer.review) == 0) {
  rate.ind <- data.frame()
  } else{
  #overall rating
  rate.ov <-
  beer.review %>% html_nodes(".BAscore_norm") %>% html_text()
  
  #review info
  rate.ind <-
  beer.review %>% html_nodes("br+ .muted") %>% html_text()
  
  rate.ind <- str_split_fixed(rate.ind, fixed("|"), n = 5)
  rate.ind <- data.frame(rate.ind)
  names(rate.ind) <- c("look", "smell", "taste", "feel", "overall")
  rate.ind <-
  rate.ind %>% mutate_all(funs(str_extract_all(
  ., pattern = "[\\d.]+", simplify = TRUE
  )))
  rate.ind <- data.frame(rate.ind)
  rate.ind$look <- c(rate.ind$look)
  rate.ind$smell <- c(rate.ind$smell)
  rate.ind$taste <- c(rate.ind$taste)
  rate.ind$feel <- c(rate.ind$feel)
  rate.ind$overall <- c(rate.ind$overall)
  rate.ind <- rate.ind[which(rate.ind$smell != ""),]
  
  beer.id <-
  str_split_fixed(str_split_fixed(beer.urls, "/beer/profile/", n = 2)[, 2], "/", n = 2)[,2]
  beer.id <-
  str_extract_all(beer.id, pattern = "[\\d.]+", simplify = TRUE)[,1]
  brewery.id <-
  str_split_fixed(beer.urls, paste0("/beer/profile/"), n = 2)[, 2]
  brewery.id <- str_split_fixed(brewery.id, "/", n = 2)[, 1]
  #date
  rate.date <-
  beer.review %>% html_nodes(".username+ a") %>% html_text()
  rate.date <-rate.date[1:length(rate.ind$smell)]
  #certain reviews don't have raitings, need to screeen them out for older reviews
  rate.ind$Date <- c(rate.date)
  rate.ind$beer.id <- c(beer.id)
  rate.ind$brewery.id <- c(brewery.id)
  rate.ind <- as.data.frame(rate.ind)
  }
  return(rate.ind)
  
}

#beer.urls <- "https://www.beeradvocate.com//beer/profile/35/104/"
beer.urls <- brewery$beer_urls[1]
grab_all_pages <- function(beer.urls) {
  beer <- read_html(as.character(beer.urls))
  num.reviews <-
  beer %>% html_nodes("div:nth-child(17) b:nth-child(1)") %>% 
    html_text() %>% str_extract_all(., pattern = "[\\d.]+", simplify = TRUE) %>%
    collapse(.) %>% as.numeric(.)
  page.seq <- seq(0, num.reviews, by = 25)
  beer.url.pages <-
  paste0(beer.urls, "?view=beer&sort=&start=", page.seq)
  rate.ind <- beer.url.pages %>% map_df(grab_reviews)
  return(rate.ind)
}

beer.url.pages %>% map_df(grab_reviews)


brewery_review_wrapper <- function(brewery.id.list){
  brewery <- tryCatch(scrape_beer(brew_id = brewery.id.list), error = function(e){NA})
  if (is.na(brewery)){}else{
  brew_id <- brewery.id.list
  #beer.reviews <- as.character(brewery$beer_urls) %>% map_df(grab_reviews)
  beer.reviews <- as.character(brewery$beer_urls) %>% map_df(grab_all_pages)
  beer.reviews$beer.id<-as.numeric(beer.reviews$beer.id)
  brewery$beer.id <- as.numeric(as.character(brewery$beer.id))
  brewery$brewery.id <- as.numeric(as.character(brewery$brewery.id))
  beer.reviews$brewery.id<-as.numeric(beer.reviews$brewery.id)
  beer.reviews <- left_join(beer.reviews, brewery, by = c("beer.id", "brewery.id"))
  write_csv(beer.reviews,unique(glue("brewery_review_{brewery$brewery.id}.csv")))}
}



```

```{r}
brewery.id.list[3:4] %>% map_df(brewery_review_wrapper)


brewery <- scrape_beer(brew_id = 35)

ber

beer.urls <- brewery$beer_urls[4]
beer <- read_html(as.character(beer.urls))
  num.reviews <-
  beer %>% html_nodes("div:nth-child(17) b:nth-child(1)") %>% 
    html_text() %>% str_extract_all(., pattern = "[\\d.]+", simplify = TRUE) %>%
    collapse(.) %>% as.numeric(.)
  page.seq <- seq(0, num.reviews, by = 25)
  beer.url.pages <-
  paste0(beer.urls, "?view=beer&sort=&start=", page.seq)
  rate.ind <- beer.url.pages %>% map_df(grab_reviews)

View(brewery)

grab_all_pages <- function(beer.urls) {
  beer <- read_html(as.character(beer.urls))
  num.reviews <-
  beer %>% html_nodes("div:nth-child(17) b:nth-child(1)") %>% 
    html_text() %>% str_extract_all(., pattern = "[\\d.]+", simplify = TRUE) %>%
    collapse(.) %>% as.numeric(.)
  page.seq <- seq(0, num.reviews, by = 25)
  beer.url.pages <-
  paste0(beer.urls, "/?view=beer&sort=&start=", page.seq)
  rate.ind <- beer.url.pages %>% map_df(grab_reviews)
  return(rate.ind)
}



unique(glue("brewery_review_{beer.reviews$brewery.id}"))[!is.na()]
dim(brewery)

grab_all_pages <- function(beer.urls) {
  beer <- read_html(as.character(beer.urls))
  num.reviews <-
  beer %>% html_nodes("div:nth-child(17) b:nth-child(1)") %>% 
    html_text() %>% str_extract_all(., pattern = "[\\d.]+", simplify = TRUE) %>%
    collapse(.) %>% as.numeric(.)
  page.seq <- seq(0, num.reviews, by = 25)
  beer.url.pages <-
  paste0(beer.urls, "/?view=beer&sort=&start=", page.seq)
  rate.ind <- beer.url.pages %>% map_df(grab_reviews)
  return(rate.ind)
}




beer.urls <- brewery$beer_urls[4]
beer <- read_html(as.character(beer.urls))
  num.reviews <-
  beer %>% html_nodes("div:nth-child(17) b:nth-child(1)") %>% 
    html_text() %>% str_extract_all(., pattern = "[\\d.]+", simplify = TRUE) %>%
    collapse(.) %>% as.numeric(.)
  page.seq <- seq(0, num.reviews, by = 25)
  beer.url.pages <-
  paste0(beer.urls, "?view=beer&sort=&start=", page.seq)
  rate.ind <- beer.url.pages %>% map_df(grab_reviews)

brewery$beer_urls[1:10] %>% map_df(grab_all_pages)

brewery$

```

